// esbuild config for folder-tag-sync-test-fixtures
//
// This repo lives at folder-tag-sync-dev-vault/.obsidian/plugins/folder-tag-sync-test-fixtures/
// so main.js at the repo root IS where Obsidian loads it from.
// No post-build copy step needed.

import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';

const banner = `/* Folder Tag Sync Test Fixtures — generated by esbuild */`;
const prod = process.argv[2] === 'production';

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: ['obsidian', 'electron', ...builtins],
  format: 'cjs',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
  console.log('👀 Watching for changes...');
}
