import { Notice, Plugin, TFile, TFolder } from 'obsidian';
import {
  PARA_FILES,
  POLY_FILES,
  EDGE_FILES,
  PRESET_RULES,
  type FixtureFile,
} from './fixtures';

/**
 * Folder Tag Sync Test Fixtures
 *
 * Generates canonical test data sets for Folder Tag Sync development.
 * Commands are exposed via the command palette (Ctrl/Cmd-P).
 *
 * Design principle: every command is idempotent — running it twice produces
 * the same result. Fixtures are grouped under a root folder (`fixtures/` by
 * default) so "Clear all" can safely nuke just the generated content.
 */

interface FixturesSettings {
  rootFolder: string;
}

const DEFAULT_SETTINGS: FixturesSettings = {
  rootFolder: 'fixtures',
};

function makeFile(tags: string[], body = 'Generated by folder-tag-sync-test-fixtures.') {
  const tagLines = tags.length ? `tags:\n${tags.map((t) => `  - ${t}`).join('\n')}\n` : '';
  return `---\n${tagLines}generated_by: folder-tag-sync-test-fixtures\n---\n\n${body}\n`;
}

export default class FolderTagSyncFixturesPlugin extends Plugin {
  settings!: FixturesSettings;

  async onload() {
    await this.loadSettings();

    this.addCommand({
      id: 'generate-para',
      name: 'Generate PARA fixture set',
      callback: () => this.writeFiles(PARA_FILES, 'PARA'),
    });

    this.addCommand({
      id: 'generate-polyhierarchy',
      name: 'Generate polyhierarchy test set',
      callback: () => this.writeFiles(POLY_FILES, 'polyhierarchy'),
    });

    this.addCommand({
      id: 'generate-edge-cases',
      name: 'Generate edge-case fixture set',
      callback: () => this.writeFiles(EDGE_FILES, 'edge cases'),
    });

    this.addCommand({
      id: 'generate-all',
      name: 'Generate all fixture sets',
      callback: async () => {
        await this.writeFiles(PARA_FILES, 'PARA', false);
        await this.writeFiles(POLY_FILES, 'polyhierarchy', false);
        await this.writeFiles(EDGE_FILES, 'edge cases', false);
        new Notice('✓ All fixture sets written');
      },
    });

    this.addCommand({
      id: 'clear-fixtures',
      name: 'Clear all generated fixtures',
      callback: () => this.clearFixtures(),
    });

    this.addCommand({
      id: 'apply-preset-rules',
      name: 'Apply preset Folder Tag Sync rules',
      callback: () => this.applyPresetRules(),
    });

    console.log('folder-tag-sync-test-fixtures loaded');
  }

  async loadSettings() {
    this.settings = { ...DEFAULT_SETTINGS, ...(await this.loadData()) };
  }

  async saveSettings() {
    await this.saveData(this.settings);
  }

  async writeFiles(files: FixtureFile[], label: string, notify = true) {
    const root = this.settings.rootFolder.replace(/\/$/, '');
    let written = 0;

    for (const f of files) {
      const fullPath = root ? `${root}/${f.path}` : f.path;
      await this.ensureFolderForFile(fullPath);

      const content = makeFile(f.tags);
      const existing = this.app.vault.getAbstractFileByPath(fullPath);
      if (existing instanceof TFile) {
        await this.app.vault.modify(existing, content);
      } else {
        await this.app.vault.create(fullPath, content);
      }
      written += 1;
    }

    if (notify) new Notice(`✓ ${label}: wrote ${written} files under ${root}/`);
  }

  async ensureFolderForFile(filePath: string) {
    const parts = filePath.split('/');
    parts.pop();
    for (let i = 1; i <= parts.length; i += 1) {
      const folderPath = parts.slice(0, i).join('/');
      if (!folderPath) continue;
      const existing = this.app.vault.getAbstractFileByPath(folderPath);
      if (!existing) {
        await this.app.vault.createFolder(folderPath);
      }
    }
  }

  async clearFixtures() {
    const root = this.settings.rootFolder.replace(/\/$/, '');
    if (!root) {
      new Notice('⚠ fixtures rootFolder is empty — refusing to clear the whole vault');
      return;
    }

    const rootEntry = this.app.vault.getAbstractFileByPath(root);
    if (!rootEntry || !(rootEntry instanceof TFolder)) {
      new Notice(`No fixtures folder found at ${root}/`);
      return;
    }

    await this.app.vault.delete(rootEntry, true);
    new Notice(`✓ Cleared ${root}/`);
  }

  async applyPresetRules() {
    const mainPluginId = 'folder-tag-sync';
    const pluginsApi = (this.app as unknown as { plugins?: { plugins?: Record<string, Plugin> } }).plugins;
    if (!pluginsApi?.plugins) {
      new Notice('✗ Cannot access installed plugins API');
      return;
    }

    const ftsPlugin = pluginsApi.plugins[mainPluginId] as
      | (Plugin & { loadData: () => Promise<unknown>; saveData: (d: unknown) => Promise<void> })
      | undefined;
    if (!ftsPlugin) {
      new Notice(`✗ Folder Tag Sync plugin ("${mainPluginId}") is not installed/enabled`);
      return;
    }

    try {
      const existing = (await ftsPlugin.loadData()) as Record<string, unknown> | null;
      if (existing) {
        await ftsPlugin.saveData({
          ...existing,
          _backup_from_fixtures: existing,
          rules: PRESET_RULES.rules,
        });
      } else {
        await ftsPlugin.saveData(PRESET_RULES);
      }
      new Notice(`✓ Applied preset rules (${PRESET_RULES.rules.length}) to ${mainPluginId}`);
    } catch (err) {
      console.error('Failed to apply preset rules:', err);
      new Notice(`✗ Failed to apply preset rules: ${(err as Error).message}`);
    }
  }
}
