import { App, Notice, Plugin, TFile, TFolder } from 'obsidian';

/**
 * Folder Tag Sync Test Fixtures
 *
 * Generates canonical test data sets for Folder Tag Sync development.
 * Commands are exposed via the command palette (Ctrl/Cmd-P).
 *
 * Design principle: every command is idempotent — running it twice produces
 * the same result. Fixtures are grouped under a root folder (`fixtures/` by
 * default) so "Clear all" can safely nuke just the generated content.
 */

interface FixturesSettings {
  rootFolder: string;  // where generated fixtures live
}

const DEFAULT_SETTINGS: FixturesSettings = {
  rootFolder: 'fixtures',
};

// ─── Fixture data shapes ─────────────────────────────────────────────────────

// File content builder: takes a set of tags, returns frontmatter + body.
function makeFile(tags: string[], body = 'Generated by folder-tag-sync-test-fixtures.') {
  const tagLines = tags.length ? `tags:\n${tags.map((t) => `  - ${t}`).join('\n')}\n` : '';
  return `---\n${tagLines}generated_by: folder-tag-sync-test-fixtures\n---\n\n${body}\n`;
}

// PARA structure — the canonical 4-bucket organizational system.
const PARA_FILES: Array<{ path: string; tags: string[] }> = [
  { path: 'Projects/Q4-Roadmap/kickoff.md',       tags: ['projects/q4_roadmap'] },
  { path: 'Projects/Q4-Roadmap/brief.md',         tags: ['projects/q4_roadmap'] },
  { path: 'Projects/Q4-Roadmap/notes.md',         tags: ['projects/q4_roadmap'] },
  { path: 'Projects/Launch/plan.md',              tags: ['projects/launch'] },
  { path: 'Projects/Research/summary.md',         tags: ['projects/research'] },
  { path: 'Areas/Health/labs.md',                 tags: ['areas/health'] },
  { path: 'Areas/Finance/budget.md',              tags: ['areas/finance'] },
  { path: 'Resources/Tools/obsidian-tips.md',     tags: ['resources/tools'] },
  { path: 'Resources/Books/reading-list.md',      tags: ['resources/books'] },
  { path: 'Archive/2023/old-project.md',          tags: ['archive/2023'] },
];

// Polyhierarchy set — files that SHOULD match multiple rules when folder-tag-sync
// rules for Projects/, Time/, and Topics/ are all configured.
const POLY_FILES: Array<{ path: string; tags: string[] }> = [
  {
    path: 'Projects/Q4-Roadmap/kickoff.md',
    tags: ['projects/q4_roadmap', 'time/2024/q4/roadmap', 'topics/roadmaps/q4'],
  },
  {
    path: 'Projects/Q4-Roadmap/brief.md',
    tags: ['projects/q4_roadmap', 'time/2024/q4/roadmap', 'topics/roadmaps/q4'],
  },
];

// Edge-case set — special characters, emoji, number prefixes, deeply nested.
const EDGE_FILES: Array<{ path: string; tags: string[] }> = [
  { path: '📁 01 - Inbox/quick-capture.md',                 tags: ['inbox'] },
  { path: '98 - Archive/Old Notes (2019)/ancient.md',       tags: ['archive/2019'] },
  { path: 'Projects/Client — Acme Inc./weekly sync.md',     tags: ['projects/acme'] },
  { path: 'deeply/nested/folder/tree/very/far/down/leaf.md', tags: ['deep'] },
  { path: 'Mixed Case Folder/SNAKE_CASE_FILE.md',           tags: ['test/case'] },
];

// Preset Folder Tag Sync rules that demonstrate polyhierarchy + priority.
// Written directly to the main plugin's data.json.
const PRESET_RULES = {
  rules: [
    {
      id: 'rule-projects',
      name: 'Projects → #projects',
      enabled: true,
      priority: 10,
      direction: 'bidirectional',
      folderPattern: '^Projects/(.*)$',
      tagPattern: '^projects/(.*)$',
      folderEntryPoint: 'Projects/',
      tagEntryPoint: 'projects/',
      folderTransforms: { caseTransform: 'Title Case' as const },
      tagTransforms: { caseTransform: 'snake_case' as const, stripEmoji: true },
    },
    {
      id: 'rule-time',
      name: 'Time → #time',
      enabled: true,
      priority: 20,
      direction: 'bidirectional',
      folderPattern: '^Time/(.*)$',
      tagPattern: '^time/(.*)$',
      folderEntryPoint: 'Time/',
      tagEntryPoint: 'time/',
      folderTransforms: { caseTransform: 'none' as const },
      tagTransforms: { caseTransform: 'snake_case' as const },
    },
    {
      id: 'rule-topics',
      name: 'Topics → #topics',
      enabled: true,
      priority: 30,
      direction: 'bidirectional',
      folderPattern: '^Topics/(.*)$',
      tagPattern: '^topics/(.*)$',
      folderEntryPoint: 'Topics/',
      tagEntryPoint: 'topics/',
      folderTransforms: { caseTransform: 'Title Case' as const },
      tagTransforms: { caseTransform: 'snake_case' as const },
    },
  ],
};

// ─── Plugin ──────────────────────────────────────────────────────────────────

export default class FolderTagSyncFixturesPlugin extends Plugin {
  settings!: FixturesSettings;

  async onload() {
    await this.loadSettings();

    this.addCommand({
      id: 'generate-para',
      name: 'Generate PARA fixture set',
      callback: () => this.writeFiles(PARA_FILES, 'PARA'),
    });

    this.addCommand({
      id: 'generate-polyhierarchy',
      name: 'Generate polyhierarchy test set',
      callback: () => this.writeFiles(POLY_FILES, 'polyhierarchy'),
    });

    this.addCommand({
      id: 'generate-edge-cases',
      name: 'Generate edge-case fixture set',
      callback: () => this.writeFiles(EDGE_FILES, 'edge cases'),
    });

    this.addCommand({
      id: 'generate-all',
      name: 'Generate all fixture sets',
      callback: async () => {
        await this.writeFiles(PARA_FILES, 'PARA', false);
        await this.writeFiles(POLY_FILES, 'polyhierarchy', false);
        await this.writeFiles(EDGE_FILES, 'edge cases', false);
        new Notice('✓ All fixture sets written');
      },
    });

    this.addCommand({
      id: 'clear-fixtures',
      name: 'Clear all generated fixtures',
      callback: () => this.clearFixtures(),
    });

    this.addCommand({
      id: 'apply-preset-rules',
      name: 'Apply preset Folder Tag Sync rules',
      callback: () => this.applyPresetRules(),
    });

    console.log('folder-tag-sync-test-fixtures loaded');
  }

  async loadSettings() {
    this.settings = { ...DEFAULT_SETTINGS, ...(await this.loadData()) };
  }

  async saveSettings() {
    await this.saveData(this.settings);
  }

  // ─── Fixture generation ────────────────────────────────────────────────────

  /**
   * Write a set of fixture files under settings.rootFolder.
   * Creates folders as needed. Overwrites existing files (idempotent).
   */
  async writeFiles(
    files: Array<{ path: string; tags: string[] }>,
    label: string,
    notify = true,
  ) {
    const root = this.settings.rootFolder.replace(/\/$/, '');
    let written = 0;

    for (const f of files) {
      const fullPath = root ? `${root}/${f.path}` : f.path;
      await this.ensureFolderForFile(fullPath);

      const content = makeFile(f.tags);
      const existing = this.app.vault.getAbstractFileByPath(fullPath);
      if (existing instanceof TFile) {
        await this.app.vault.modify(existing, content);
      } else {
        await this.app.vault.create(fullPath, content);
      }
      written += 1;
    }

    if (notify) new Notice(`✓ ${label}: wrote ${written} files under ${root}/`);
  }

  /**
   * Ensure parent folders exist for a given file path.
   * Obsidian's vault.create() doesn't auto-create folders.
   */
  async ensureFolderForFile(filePath: string) {
    const parts = filePath.split('/');
    parts.pop(); // drop filename
    for (let i = 1; i <= parts.length; i += 1) {
      const folderPath = parts.slice(0, i).join('/');
      if (!folderPath) continue;
      const existing = this.app.vault.getAbstractFileByPath(folderPath);
      if (!existing) {
        await this.app.vault.createFolder(folderPath);
      }
    }
  }

  /**
   * Delete everything under the fixtures root folder.
   * Only touches files under settings.rootFolder — never the whole vault.
   */
  async clearFixtures() {
    const root = this.settings.rootFolder.replace(/\/$/, '');
    if (!root) {
      new Notice('⚠ fixtures rootFolder is empty — refusing to clear the whole vault');
      return;
    }

    const rootEntry = this.app.vault.getAbstractFileByPath(root);
    if (!rootEntry || !(rootEntry instanceof TFolder)) {
      new Notice(`No fixtures folder found at ${root}/`);
      return;
    }

    await this.app.vault.delete(rootEntry, true);
    new Notice(`✓ Cleared ${root}/`);
  }

  // ─── Rule preset ───────────────────────────────────────────────────────────

  /**
   * Write the preset rule set directly into Folder Tag Sync's data.json.
   * Backs up the existing config first.
   */
  async applyPresetRules() {
    const mainPluginId = 'folder-tag-sync';

    // Reach into the installed main plugin via app.plugins
    const pluginsApi = (this.app as any).plugins;
    if (!pluginsApi || !pluginsApi.plugins) {
      new Notice('✗ Cannot access installed plugins API');
      return;
    }

    const ftsPlugin = pluginsApi.plugins[mainPluginId];
    if (!ftsPlugin) {
      new Notice(`✗ Folder Tag Sync plugin ("${mainPluginId}") is not installed/enabled`);
      return;
    }

    // Back up existing settings
    try {
      const existing = await ftsPlugin.loadData();
      if (existing) {
        await ftsPlugin.saveData({
          ...existing,
          _backup_from_fixtures: existing,
          rules: PRESET_RULES.rules,
        });
      } else {
        await ftsPlugin.saveData(PRESET_RULES);
      }
      new Notice(`✓ Applied preset rules (${PRESET_RULES.rules.length}) to ${mainPluginId}`);
    } catch (err) {
      console.error('Failed to apply preset rules:', err);
      new Notice(`✗ Failed to apply preset rules: ${(err as Error).message}`);
    }
  }
}
